spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:tc:mysql://localhost:3306/uniro-test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: true
map:
  api:
    key: ${google.api.key}

cors:
  allowed-origins: ${allowed-origins}

jwt:
  secret: ${JWT_SECRET}