spring:
  config:
    import: application.properties
  datasource:
    hikari:
      maximum-pool-size: 30
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: 6379
map:
  api:
    key: ${google.api.key}

management:
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: info, health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

cors:
  allowed-origins: ${allowed-origins}

jwt:
  secret: ${JWT_SECRET}