spring:
  datasource:
    url: jdbc:h2:tcp:testdb  # H2 메모리 DB
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
