spring:
  datasource:
    hikari:
      maximum-pool-size: 30
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uniro-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
        show_sql: true
    open-in-view: false
    #defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
map:
  api:
    key: ${google.api.key}

management:
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: info, health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

cors:
  allowed-origins: ${allowed-origins}

jwt:
  secret: ${JWT_SECRET}