version: '3.8'

services:
  spring-green:
    image: uniro5th/uniro-docker-repo:develop
    container_name: spring-green
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_network1

  spring-blue:
    image: uniro5th/uniro-docker-repo:develop
    container_name: spring-blue
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    ports:
      - "8081:8080"
    networks:
      - my_network1

networks:
  my_network1:
    external: true
